name: Infrasturcture Deployment
on:
    workflow_dispatch:
        inputs:
            selection:
                description: Select the type of deployment
                required: true
                type: choice
                default: "plan"
                options:
                    - "apply"
                    - "destroy"
                    - "plan"
env:
    AWS_REGION: ap-south-1
    path: ver2/infra
    terraform_version: 1.15.3
  

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout
             uses: actions/checkout@v3
           - name: Configure AWS credentials
             uses: aws-actions/configure-aws-credentials@v2
             with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: ${{ env.AWS_REGION }}
           - name: Setup Terraform 
             uses: hashicorp/setup-terraform@v2
             with:
                 terraform_version: ${{ env.terraform_version }}
                 command: init
           - name: Init Terraform 
             uses: hashicorp/setup-terraform@v2
             with:
                 run: terraform init
           - name: Terraform Plan
             if: ${{ github.event.inputs.selection == 'plan' }}
             working-directory: ${{ env.path }}
             run: terraform plan
           - name: Terraform Apply
             if: ${{ github.event.inputs.selection == 'apply' }}
             working-directory: ${{ env.path }}
             run: terraform apply
           - name: Terraform Destroy
             if: ${{ github.event.inputs.selection == 'destroy' }}
             working-directory: ${{ env.path }}
             run: terraform destroy
            
